version: '2'
services:
    backend:
        container_name: 192.168.0.29
        build:
            context: backend
        image: 192.168.0.29:latest
        depends_on:
            - db
        ports:
            - "5030:5000"
        networks:
            default:
                aliases:
                    - back-end

    frontend:
        container_name: test_frontend
        build:
            context: frontend
        image: test_frontend:latest
        depends_on:
            - backend
        ports:
            - "8080:80"
        networks:
            default:
                aliases:
                    - front-end

    db:
        container_name: test_db
        image: postgres
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=backend
            - POSTGRES_PASSWORD=backend
            - POSTGRES_DB=proekt