POST http://localhost:5000/auth/register HTTP/1.1
content-type: application/json

{
    "username":"asd",
    "password":"asd",
    "ime":"david",
    "prezime":"david",
    "isAdmin":true
}





###
POST http://localhost:5000/storno/reasociraj HTTP/1.1

###
POST http://localhost:5000/faktura/platiFaktura HTTP/1.1
Content-Type: application/json

{

    "fakturaid":"2",
    "platena":true
   

}

    
###
POST http://localhost:5000/faktura/toExcel HTTP/1.1
Content-Type: application/json

{
    "fakturaId":"1"
}



###
POST http://localhost:5000/auth/login HTTP/1.1
content-type: application/json

{
    "username":"asd",
    "password":"asd"
}

###
POST http://localhost:5000/faktura/generirajFakturi HTTP/1.1
Content-Type: application/json

{
    "id":"5",   
    "mesec":3,
    "godina":2021
}
